// Manual definitions for Windows Setup API types and P/Invoke methods
// that CsWin32 v0.3.275 fails to generate on certain SDK/CI configurations.
//
// Types generated BY CsWin32 (NOT redefined here):
//   HDEVINFO, SetupDiDestroyDeviceInfoListSafeHandle, SETUP_DI_REGISTRY_PROPERTY,
//   GUID_DEVCLASS_PORTS, GUID_DEVICE_BATTERY

using System;
using System.Runtime.InteropServices;

#nullable enable

namespace Windows.Win32.Devices.DeviceAndDriverInstallation
{
    [StructLayout(LayoutKind.Sequential)]
    internal struct SP_DEVINFO_DATA
    {
        public uint cbSize;
        public Guid ClassGuid;
        public uint DevInst;
        public nint Reserved;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct SP_DEVICE_INTERFACE_DATA
    {
        public uint cbSize;
        public Guid InterfaceClassGuid;
        public uint Flags;
        public nint Reserved;
    }

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    internal unsafe struct SP_DEVICE_INTERFACE_DETAIL_DATA_W
    {
        public uint cbSize;
        public fixed char DevicePath[1];
    }

    [Flags]
    internal enum SETUP_DI_GET_CLASS_DEVS_FLAGS : uint
    {
        DIGCF_DEFAULT = 0x00000001,
        DIGCF_PRESENT = 0x00000002,
        DIGCF_ALLCLASSES = 0x00000004,
        DIGCF_PROFILE = 0x00000008,
        DIGCF_DEVICEINTERFACE = 0x00000010,
    }
}

namespace Windows.Win32
{
    internal static partial class PInvoke
    {
        [DllImport("setupapi.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        [return: MarshalAs(UnmanagedType.Bool)]
        internal static extern unsafe bool SetupDiEnumDeviceInterfaces(
            SetupDiDestroyDeviceInfoListSafeHandle DeviceInfoSet,
            void* DeviceInfoData,
            in Guid InterfaceClassGuid,
            uint MemberIndex,
            ref Devices.DeviceAndDriverInstallation.SP_DEVICE_INTERFACE_DATA DeviceInterfaceData);

        [DllImport("setupapi.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        [return: MarshalAs(UnmanagedType.Bool)]
        internal static extern unsafe bool SetupDiGetDeviceInterfaceDetail(
            Devices.DeviceAndDriverInstallation.HDEVINFO DeviceInfoSet,
            Devices.DeviceAndDriverInstallation.SP_DEVICE_INTERFACE_DATA* DeviceInterfaceData,
            Devices.DeviceAndDriverInstallation.SP_DEVICE_INTERFACE_DETAIL_DATA_W* DeviceInterfaceDetailData,
            uint DeviceInterfaceDetailDataSize,
            uint* RequiredSize,
            void* DeviceInfoData);

        [DllImport("setupapi.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        [return: MarshalAs(UnmanagedType.Bool)]
        internal static extern bool SetupDiEnumDeviceInfo(
            SetupDiDestroyDeviceInfoListSafeHandle DeviceInfoSet,
            uint MemberIndex,
            ref Devices.DeviceAndDriverInstallation.SP_DEVINFO_DATA DeviceInfoData);

        [DllImport("setupapi.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        [return: MarshalAs(UnmanagedType.Bool)]
        internal static extern unsafe bool SetupDiGetDeviceRegistryProperty(
            SetupDiDestroyDeviceInfoListSafeHandle DeviceInfoSet,
            in Devices.DeviceAndDriverInstallation.SP_DEVINFO_DATA DeviceInfoData,
            Devices.DeviceAndDriverInstallation.SETUP_DI_REGISTRY_PROPERTY Property,
            uint* PropertyRegDataType,
            byte* PropertyBuffer,
            uint PropertyBufferSize,
            uint* RequiredSize);
    }
}
